config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :merchants, except: %i[new create]

  root to: 'merchants#index'

  namespace :api do
    post 'authenticate', to: 'authentication#authenticate'

    namespace :v1, defaults: { format: 'json' } do
      post 'transactions', to: 'transactions#create'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    elsif user.merchant?
      can :manage, Transaction, user_id: user.id
      can %i[read update], Merchant, id: user.id
      cannot :index, Merchant
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < User
  before_validation :add_merchant_role
  has_many :transactions, dependent: :restrict_with_exception, foreign_key: 'user_id'

  enum status: { active: 'active', inactive: 'inactive' }

  private

  def add_merchant_role
    self.role_id = Role.find_or_create_by(name: ::Role::MERCHANT).id
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  ADMIN = 'admin'.freeze
  MERCHANT = 'merchant'.freeze
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :merchant, foreign_key: 'user_id'
  after_initialize :defaults

  enum status: {
    approved: 'approved',
    refunded: 'refunded',
    reversed: 'reversed',
    error: 'error'
  }

  def initialize(*args)
    # Avoid to initialize parent transaction without a type
    raise "Cannot directly instantiate a #{self.class.name}" if self.class == Transaction

    super
  end

  protected

  def defaults
    return if persisted?

    self.uuid ||= SecureRandom.uuid
  end
end

app/models/transactions/authorize.rb
module Transactions
  class Authorize < ::Transaction
  end
end

app/models/transactions/charge.rb
module Transactions
  class Charge < ::Transaction
  end
end

app/models/transactions/refund.rb
module Transactions
  class Refund < ::Transaction
  end
end

app/models/transactions/reversal.rb
module Transactions
  class Reversal < ::Transaction
    def amount
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  belongs_to :role

  delegate :name, to: :role, prefix: true

  def admin?
    role_name == ::Role::ADMIN
  end

  def merchant?
    role_name == ::Role::MERCHANT
  end
end

app/controllers/api/authentication_controller.rb
module Api
  class AuthenticationController < BaseController
    skip_before_action :authenticate_request

    def authenticate
      command = Authenticate.call(params[:email], params[:password])

      if command.success?
        render json: { auth_token: command.result }
      else
        render json: { error: command.errors }, status: :unauthorized
      end
    end
  end
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ActionController::API
    include ActionController::MimeResponds

    before_action :authenticate_request

    attr_reader :current_user

    private

    def authenticate_request
      @current_user = api_authorizer(request.headers).result
      render json: { error: 'Not Authorized' }, status: 401 unless @current_user
    end

    def api_authorizer(headers)
      ::AuthorizeApiRequest.call(headers)
    end
  end
end

app/controllers/api/v1/transactions_controller.rb
module Api
  module V1
    class TransactionsController < ::Api::BaseController
      include ActionController::MimeResponds

      def create
        transaction_form = form_class.new(resource_class.new)

        if transaction_form.validate_and_save!(transaction_params)
          render json: transaction_form.model
        else
          render json: transaction_form.errors.full_messages
        end
      end

      private

      def form_class
        "::V1::Transaction::#{transaction_type}Form".constantize
      end

      def resource_class
        "::Transactions::#{transaction_type}".constantize
      end

      def transaction_type
        transaction_params[:type].capitalize
      end

      def transaction_params
        # allowed types: authorize, refund, reversal, charge
        params.fetch(:transaction).permit(:type, :user_id, :customer_phone, :customer_email, :amount, :status)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ResourceInitializer

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html', status: 403 }
      format.html { redirect_to root_for_user(current_user), alert: exception.message }
    end
  end
end

app/controllers/concerns/resource_initializer.rb
module ResourceInitializer
  extend ActiveSupport::Concern

  def after_sign_in_path_for(resource)
    root_for_user(resource)
  end

  protected

  def form_class
    raise NotImplementedError
  end

  def resource_class
    raise NotImplementedError
  end

  def resource_object
    @resource_object ||= resource_class.find(params[:id])
  end

  def form
    @form ||= form_class.new(resource_object)
  end

  def presenter_class
    raise NotImplementedError
  end

  def resource_to_presenter(resource_object)
    presenter_class.new(resource_object)
  end

  private

  def root_for_user(resource)
    if resource.admin?
      merchants_path
    elsif resource.merchant?
      merchant_path(resource)
    end
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  load_and_authorize_resource
  before_action :set_merchant, only: %i[show edit update destroy]
  before_action :form, only: %i[edit update]

  def index
    @merchants = Merchant.all.includes(:transactions)
  end

  def update
    if form.validate_and_save!(merchant_params)
      redirect_to resource_object, notice: "#{resource_class} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @merchant.destroy

    redirect_to merchants_url, notice: "#{resource_class} was successfully destroyed."
  end

  private

  def set_merchant
    @merchant = resource_object
  end

  def form_class
    ::V1::Merchant::BaseForm
  end

  def resource_class
    ::Merchant
  end

  def merchant_params
    params.fetch(:merchant).permit(:name, :description, :status, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MerchantPay
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body.bg-light.py-4
    .containter{align='center'}
      .mt-3.text-center
        = image_tag 'logo.png', class: 'd-block mx-auto', height: '60px'
      - if flash[:notice].present?
        .col-md-4.alert.alert-info = flash[:notice]
      - if flash[:alert].present?
        .col-md-4.alert.alert-danger = flash[:alert]
      = yield
      footer.page-footer.mt-5
        - if user_signed_in?
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-danger'

app/views/merchants/_form.html.slim
= simple_form_for @form do |f|
  - if @form.errors.any?
    .alert.alert-danger.text-left
      h6 = "#{pluralize(@form.errors.count, "error")} prohibited this merchant from being saved:"
      ul
        - @form.errors.full_messages.each do |message|
          li = message
  .form-inputs
    = f.input :name, label: false, placeholder: 'Merchant name'
    = f.input :email, label: false, placeholder: 'Merchant name'
    = f.input :description, label: false, placeholder: 'Merchant description', input_html: { rows: 5 }
    = f.input :status, as: :select, collection: Merchant.statuses.keys, label: false, placeholder: 'Status'

  .form-actions
    = f.button :submit, class: 'btn btn-sm btn-success'

app/views/merchants/_transaction.html.slim
tr
  td = transaction.type
  td = transaction.uuid
  td = transaction.amount
  td = transaction.status
  td = transaction.customer_phone
  td = transaction.customer_email

app/views/merchants/edit.html.slim
.text-center
  h2 Editing merchant details

.col-md-4.mt-5
  == render 'form'
  br
  => link_to 'Show', @merchant, class: 'btn btn-sm btn-info'
  =< link_to 'Back', merchants_path, class: 'btn btn-sm btn-info'

app/views/merchants/index.html.slim
.text-center
  h2 Merchants list

.col-md-6.order-md-2.mt-5
  table.table.table-striped.table-bordered
    thead
      tr
        th Name
        th Email
        th Transactions count
        th Total transactions sum
        th Status
        th Actions

    tbody
      - @merchants.each do |merchant|
        tr class=(merchant.active? ? '' : 'table-danger')
          td = link_to merchant.name, merchant
          td = merchant.email
          td = merchant.transactions.count
          td = merchant.total_transaction_sum
          td = merchant.status
          td
            =< link_to 'Edit', edit_merchant_path(merchant), class: 'btn btn-sm btn-success'
            =< link_to 'Destroy', merchant, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-sm btn-danger' unless merchant.transactions.present?

app/views/merchants/show.html.slim
.text-center
  h2
    = "#{@merchant.name} details"
dl.row.text-left.col-md-8.mt-5
  dt.col-sm-3 Name
  dd.col-sm-9 = @merchant.name
  dt.col-sm-3 Description
  dd.col-sm-9 = @merchant.description
  dt.col-sm-3 Email
  dd.col-sm-9 = @merchant.email
  dt.col-sm-3 Total transactions sum
  dd.col-sm-9 = @merchant.total_transaction_sum
  dt.col-sm-3 Status
  dd.col-sm-9 = @merchant.status

.col-md-8.mt-5
  table.table.table-striped.table-bordered
    thead
      tr
        th Type
        th UUID
        th Amount
        th Status
        th Customer phone
        th Customer email

    tbody
      - @merchant.transactions.each do |transaction|
        = render partial: 'transaction', locals: { transaction: transaction }
=< link_to 'Edit', edit_merchant_path(@merchant), class: 'btn btn-sm btn-success'
=< link_to 'Back', merchants_path, class: 'btn btn-primary btn-sm' if can?(:index, Merchant)